project:
  type: website
  render:
    - "*.md"
    - README.md
    - resources/README.md
    - content/README.md

website:
  title: "Open Source Undefined"
  navbar:
    left:
      - href: README.md
        text: Home

    tools:
      - icon: github
        href: https://github.com/Open-Models/Open-Source-Undefined
      - icon: book
        href: https://www.zotero.org/groups/5352918/open_source_undefined/library
      - icon: chat-right-dots
        href: https://github.com/Open-Models/Open-Source-Undefined/discussions
      - icon: cc-circle
        href: https://creativecommons.org/publicdomain/zero/1.0/

  sidebar:
    style: "docked"
    contents:
      - text: "Content"
        href: content/README.md
      - section: "Resources"
        href: resources/README.md
        contents:
          - resources/open-source-reflections.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



